version: '3'


services:
  sentinel:
    build: ./sentinel
    container_name: sentinel
    volumes:
      - ./.hcccore:/.hcccore
      - ./sentinel:/sentinel
    env_file:
      - .env
    expose: # new
      - 5555
    networks:
      main:
        ipv4_address: 172.16.238.10
    restart: 'always'

  hccd:
    image: hcccrypto/hccd
    container_name: hccd
    volumes:
      - ./.hcccore:/root/.hcccore
    ports:
      - 8888:8888
      - 9998:9998
    command:
      - hccd
      - -rpcallowip=172.16.238.10
    expose: # new
      - 8888
      - 9998
    depends_on:
      - sentinel
    networks:
      main:
        ipv4_address: 172.16.238.11
    restart: 'always'

networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24