version: '3'


services:
  hccd:
    build: ./.hcccore
    container_name: hccd
    volumes:
      - ./.hcccore:/root/.hcccore
    ports:
      - 8888:8888
      - 9998:9998
    command:
      - hccd
    expose:  # new
      - 8888
      - 9998
    environment:
      RPCALLOWIP: sentinel
      RPCUSER: $RPCUSER
      RPCPASSWORD: $RPCPASSWORD
      ADDNODE: $ADDNODE
      EXTERNALIP: $EXTERNALIP
      MASTERNODEBLSPRIVKEY: $MASTERNODEBLSPRIVKEY
      RPCBIND: $RPCBIND
    depends_on:
      - sentinel
    restart: 'always'

  sentinel:
    build: ./sentinel
    container_name: sentinel
    volumes:
      - ./.hcccore:/.hcccore
      - ./sentinel:/sentinel
    restart: 'always'