version: '3'


services:
  sentinel:
    build: ./sentinel
    container_name: sentinel
    volumes:
      - ./.hcccore:/.hcccore
      - ./sentinel:/sentinel
    env_file:
      - .env
    expose: # new
      - 5555
    restart: 'always'

  hccd:
    image: hcccrypto/hccd
    container_name: hccd
    volumes:
      - ./.hcccore:/root/.hcccore
    ports:
      - 8888:8888
      - 9998:9998
    command:
      - hccd
      - -rpcallowip=sentinel
    environment:
      sentinel: sentinel
    links:
      - sentinel
    expose: # new
      - 8888
      - 9998
    depends_on:
      - sentinel
    restart: 'always'