version: '3'


services:
  hccd:
    image: hcccrypto/hccd
    container_name: hccd
    volumes:
      - ./.hcccore:/root/.hcccore
    ports:
      - 8888:8888
      - 9998:9998
    environment:
      rpcallowip: sentinel
    command:
      - hccd
    expose:  # new
      - 8888
      - 9998
    links:
      - sentinel:sentinel
    depends_on:
      - sentinel
    restart: 'always'

  sentinel:
    build: ./sentinel
    container_name: sentinel
    volumes:
      - ./.hcccore:/.hcccore
      - ./sentinel:/sentinel
    env_file:
      - .env
    environment:
      rpcuser: $rpcuser
      rpcpassword: $rpcpassword
      addnode: $addnode
      externalip: $externalip
      masternodeblsprivkey: $masternodeblsprivkey
      rpcbind: $rpcbind
    restart: 'always'